# Azure Pipelines configuration
pool:
  vmImage: windows-latest

steps:
- pwsh: |
    Set-Executionpolicy RemoteSigned -Scope CurrentUser
    iwr -useb get.scoop.sh | iex
  displayName: Install Scoop
- pwsh: |
    Copy-Item -Path . -Destination $env:SCOOP\buckets\xn -Recurse
    $USER = [EnvironmentVariableTarget]::User
    $OLD_PATH = [Environment]::GetEnvironmentVariable('Path', $USER)
    $NEW_PATH += $OLD_PATH + ";" + "$env:SCOOP\shims"
    [Environment]::SetEnvironmentVariable('Path', $OLD_PATH, $USER)
    echo "SCOOP is $env:SCOOP"
    echo "Path is $env:Path"
  displayName: Copy self as bucket and refresh env
- pwsh: |
    .\bin\Check-Version.ps1
  displayName: Check version of apps in bucket
- pwsh: |
    .\test\Install-Test.ps1
  displayName: Test process installing apps
